In [1]:
import numpy as np

In [3]:
X = np.random.normal(loc=1, scale=10, size =(1000,50))
X

array([[ 12.65697626,  -0.26296635,  -4.90969287, ..., -12.47963746,
         -8.53023486,  -6.44135626],
       [ 17.1400813 ,   5.16923641,   3.00697114, ...,  19.69157653,
          9.69093028,  16.21336648],
       [ -2.94423548,   3.43674247,   4.64926408, ...,  11.21967876,
          8.24814093,   7.39306594],
       ...,
       [ -1.59657914,   8.92645072,  14.70339113, ...,   0.10647755,
         -8.96274668, -15.10013057],
       [ -2.36689137, -11.31225283,   5.86810876, ...,  -2.60621692,
         12.37341471,   3.61209704],
       [  8.6717043 ,  -6.4224073 ,  -1.43921841, ...,  -4.99701262,
          0.56242096,   6.72512982]])

In [4]:
m = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = ((X - m) / std)
X_norm

array([[ 1.12032718, -0.09595134, -0.61175712, ..., -1.32663689,
        -0.93351154, -0.69573112],
       [ 1.55352095,  0.45314586,  0.18790538, ...,  1.87424181,
         0.88933571,  1.5080409 ],
       [-0.38718774,  0.27802214,  0.35379345, ...,  1.03132935,
         0.74499892,  0.65003298],
       ...,
       [-0.25696631,  0.8329321 ,  1.36936116, ..., -0.0743799 ,
        -0.97678006, -1.53802633],
       [-0.33140009, -1.21283384,  0.47690899, ..., -0.34427976,
         1.15769173,  0.28223358],
       [ 0.73523806, -0.71855913, -0.26120437, ..., -0.58215226,
        -0.0238813 ,  0.58505849]])

In [5]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [6]:
r = np.sum(Z,axis=1)
np.nonzero(r>10)

(array([1, 4, 5], dtype=int64),)

In [8]:
A= B = np.eye(3)
np.vstack((A,B))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [2]:
900/950

0.9473684210526315